import { createProduct } from '@/lib/actions/products'

export default function NewProductPage() {
  return <ProductBaseForm title="Nuevo Product Base" action={createProduct} />
}

export function ProductBaseForm({ title, action, product }: { title: string; action: (formData: FormData) => Promise<void>; product?: any }) {
  return <div className="mx-auto max-w-3xl space-y-6"><header><h1 className="text-2xl font-bold text-gray-950">{title}</h1><p className="mt-1 text-sm text-gray-600">Definí el Product Base. Las opciones y precios de un configurable se cargan mediante su ConfiguratorVersion.</p></header><form action={action} className="space-y-5 rounded-2xl border border-gray-200 bg-white p-6"><label className="block text-sm font-medium">Nombre<input name="name" required defaultValue={product?.name} className="input mt-1 w-full" /></label><label className="block text-sm font-medium">Slug<input name="slug" defaultValue={product?.slug} className="input mt-1 w-full" /></label><label className="block text-sm font-medium">Descripción<textarea name="description" defaultValue={product?.description || ''} className="input mt-1 min-h-24 w-full" /></label><div className="grid gap-4 sm:grid-cols-3"><label className="block text-sm font-medium">Tipo de catálogo<select name="catalogType" defaultValue={product?.catalogType || 'COSA'} className="input mt-1 w-full"><option value="COSA">Cosa</option><option value="DESARROLLO">Desarrollo</option></select></label><label className="block text-sm font-medium">Modalidad<select name="modality" defaultValue={product?.modality || 'CONSULTAR'} className="input mt-1 w-full"><option value="CONFIGURABLE">Configurable</option><option value="DIRECTO">Directo</option><option value="CONSULTAR">Consultar</option></select></label><label className="block text-sm font-medium">Motor<select name="engine" defaultValue={product?.engine || ''} className="input mt-1 w-full"><option value="">Sin motor</option><option value="IMPRESOS_PACKAGING">Impresos & Packaging</option><option value="PRESENCIA_FISICA">Presencia física</option><option value="TEXTIL">Textil</option><option value="DIGITAL">Digital</option><option value="CAMPANAS">Campañas</option></select></label></div><label className="block text-sm font-medium">Qué es<textarea name="whatIs" defaultValue={product?.whatIs || ''} className="input mt-1 min-h-20 w-full" /></label><label className="block text-sm font-medium">Para qué sirve<textarea name="purpose" defaultValue={product?.purpose || ''} className="input mt-1 min-h-20 w-full" /></label><label className="block text-sm font-medium">Nota de consulta<textarea name="consultationNote" defaultValue={product?.consultationNote || ''} className="input mt-1 min-h-20 w-full" /></label><button className="btn-primary">Guardar</button></form></div>
}
