'use client'

import { FormEvent, useState, useTransition } from 'react'
import { Pencil, Plus, Trash2, X } from 'lucide-react'
import { deleteNeed, deleteSituation, saveNeed, saveSituation } from './actions'

type Reference = { id: string; name: string }
type Situation = Reference & { slug: string; icon: string | null; description: string | null; active: boolean; order: number; businessTypes: Reference[]; needs: Reference[]; _count: { needs: number } }
type Need = Reference & { slug: string; description: string | null; active: boolean; order: number; businessTypes: Reference[]; situations: Reference[]; _count: { products: number } }

function slug(value: string) { return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
function Checks({ label, name, values, selected }: { label: string; name: string; values: Reference[]; selected: Reference[] }) {
  const chosen = new Set(selected.map((item) => item.id))
  return <div><p className="mb-2 text-xs font-semibold text-gray-600">{label}</p><div className="flex flex-wrap gap-2">{values.map((value) => <label key={value.id} className="cursor-pointer rounded-full border border-gray-200 px-3 py-1.5 text-xs font-medium text-gray-700 has-[:checked]:border-[#ED164F] has-[:checked]:bg-[#FEF1F5] has-[:checked]:text-[#C2103F]"><input className="sr-only" type="checkbox" name={name} value={value.id} defaultChecked={chosen.has(value.id)} />{value.name}</label>)}</div></div>
}

export default function DiscoveryAdminClient({ situations, needs, businessTypes }: { situations: Situation[]; needs: Need[]; businessTypes: Reference[] }) {
  const [editingSituation, setEditingSituation] = useState<Situation | null>(null)
  const [editingNeed, setEditingNeed] = useState<Need | null>(null)
  const [pending, startTransition] = useTransition()
  const submit = (event: FormEvent<HTMLFormElement>, action: (data: FormData) => Promise<void>, close: () => void) => { event.preventDefault(); startTransition(async () => { await action(new FormData(event.currentTarget)); close() }) }
  return <div className="mx-auto max-w-7xl space-y-7">
    <header><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#ED164F]">Arquitectura comercial</p><h1 className="mt-2 text-3xl font-black text-gray-950">Situaciones y necesidades</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-600">Administrá el recorrido Rubro → Situación → Necesidad → Oferta. Las ofertas se asocian desde cada ficha de producto.</p></header>
    <div className="grid gap-6 xl:grid-cols-2">
      <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-gray-950">Situaciones</h2><p className="text-xs text-gray-500">Lo que está pasando en el negocio.</p></div><button onClick={() => setEditingSituation({ id: '', name: '', slug: '', icon: '', description: '', active: true, order: situations.length, businessTypes: [], needs: [], _count: { needs: 0 } })} className="btn-primary !px-3 !py-2 !text-xs"><Plus size={15}/> Nueva</button></div><div className="space-y-2">{situations.map((item) => <div key={item.id} className="rounded-xl border border-gray-100 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-gray-900">{item.icon} {item.name}</p><p className="mt-1 text-xs text-gray-500">{item._count.needs} necesidades · {item.businessTypes.map((x) => x.name).join(', ') || 'sin rubro'}</p></div><div className="flex gap-1"><button onClick={() => setEditingSituation(item)} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100"><Pencil size={15}/></button><form action={deleteSituation}><input type="hidden" name="id" value={item.id}/><button onClick={(e) => { if (!confirm(`¿Eliminar "${item.name}"?`)) e.preventDefault() }} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></form></div></div></div>)}</div></section>
      <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-gray-950">Necesidades</h2><p className="text-xs text-gray-500">Lo concreto que la persona busca resolver.</p></div><button onClick={() => setEditingNeed({ id: '', name: '', slug: '', description: '', active: true, order: needs.length, businessTypes: [], situations: [], _count: { products: 0 } })} className="btn-primary !px-3 !py-2 !text-xs"><Plus size={15}/> Nueva</button></div><div className="space-y-2">{needs.map((item) => <div key={item.id} className="rounded-xl border border-gray-100 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-gray-900">{item.name}</p><p className="mt-1 text-xs text-gray-500">{item._count.products} ofertas · {item.situations.map((x) => x.name).join(', ') || 'sin situación'}</p></div><div className="flex gap-1"><button onClick={() => setEditingNeed(item)} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100"><Pencil size={15}/></button><form action={deleteNeed}><input type="hidden" name="id" value={item.id}/><button onClick={(e) => { if (!confirm(`¿Eliminar "${item.name}"?`)) e.preventDefault() }} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={15}/></button></form></div></div></div>)}</div></section>
    </div>
    {editingSituation && <Editor title="Situación" item={editingSituation} onClose={() => setEditingSituation(null)} onSubmit={(e) => submit(e, saveSituation, () => setEditingSituation(null))} pending={pending}><div className="grid gap-4 sm:grid-cols-2"><Field label="Icono" name="icon" value={editingSituation.icon || ''}/><Field label="Orden" name="order" value={String(editingSituation.order)} type="number"/></div><Checks label="Rubros" name="businessTypeIds" values={businessTypes} selected={editingSituation.businessTypes}/><Checks label="Necesidades de esta situación" name="needIds" values={needs} selected={editingSituation.needs}/></Editor>}
    {editingNeed && <Editor title="Necesidad" item={editingNeed} onClose={() => setEditingNeed(null)} onSubmit={(e) => submit(e, saveNeed, () => setEditingNeed(null))} pending={pending}><Field label="Orden" name="order" value={String(editingNeed.order)} type="number"/><Checks label="Rubros" name="businessTypeIds" values={businessTypes} selected={editingNeed.businessTypes}/><Checks label="Situaciones relacionadas" name="situationIds" values={situations} selected={editingNeed.situations}/></Editor>}
  </div>
}
function Field({ label, name, value, type = 'text' }: { label: string; name: string; value: string; type?: string }) { return <label className="block text-sm font-semibold text-gray-700">{label}<input name={name} type={type} defaultValue={value} className="input mt-1 w-full"/></label> }
function Editor({ title, item, children, onClose, onSubmit, pending }: { title: string; item: Situation | Need; children: React.ReactNode; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; pending: boolean }) { const [name, setName] = useState(item.name); return <div className="fixed inset-0 z-[70] overflow-y-auto bg-black/35 p-4"><form onSubmit={onSubmit} className="mx-auto my-8 max-w-2xl space-y-4 rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-gray-950">{item.id ? `Editar ${title.toLowerCase()}` : `Nueva ${title.toLowerCase()}`}</h2><button type="button" onClick={onClose} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><X size={18}/></button></div><input type="hidden" name="id" value={item.id}/><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-gray-700">Nombre<input required name="name" value={name} onChange={(e) => setName(e.target.value)} className="input mt-1 w-full"/></label><Field label="URL" name="slug" value={item.slug || slug(name)}/></div><label className="block text-sm font-semibold text-gray-700">Descripción<textarea name="description" defaultValue={item.description || ''} rows={3} className="input mt-1 w-full resize-none"/></label><label className="flex items-center gap-2 text-sm font-semibold text-gray-700"><input name="active" type="checkbox" defaultChecked={item.active}/> Visible públicamente</label>{children}<button disabled={pending} className="btn-primary w-full">{pending ? 'Guardando…' : 'Guardar'}</button></form></div>}
